name: Reportar Bug
description: Encontrou um erro ou crash no plugin/mod?
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Por favor, preencha o máximo de informações possível para podermos reproduzir o problema.

  - type: input
    id: mc_version
    attributes:
      label: Versão do Minecraft
      description: Qual versão do Minecraft você está rodando?
      placeholder: "1.21.1"
    validations:
      required: true

  - type: dropdown
    id: software
    attributes:
      label: Software do Servidor / Modloader
      description: Onde o projeto está rodando?
      options:
        - Paper
        - Purpur
        - Spigot
        - Fabric
        - Forge
        - NeoForge
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Problema
      description: O que aconteceu de errado?
      placeholder: "Quando eu digito /comando, o servidor apresenta um erro no console..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Erros do Console
      description: Cole o link do Pastebin, mclo.gs ou similar contendo o erro. Não cole o erro gigante diretamente aqui!
      placeholder: "https://mclo.gs/..."
    validations:
      required: false