blank_issues_enabled: false
contact_links:
  - name: Suporte no Discord
    url: https://discord.gg/2PvYZfjWDf
    about: Precisa de ajuda para configurar ou tem uma dúvida rápida? Entre no nosso Discord.